name: Automated Module Graph

on:
  push:
      branches: [ "develop", "master" ]

jobs:
  generate-dependency-graph:
    name: Generate Dependency Graph
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1

      - name: Generate Dependency Graph
        run: ./gradlew projectDependencyGraph

      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated Graph Change
          branch: ${{ github.ref }}